### ISSUE TITLE
Das Paket konnte nicht installiert werden. Es wurden keine funktionsfähigen Plugins gefunden

### ISSUE THREAD

**Issue by Mirko45326** [flotte-berlin/commons-booking-map#1]
Plugin-Installation aus Datei: commons-booking-map-master.zip

Entpacken des Pakets …

Das Plugin wird installiert …

Das Paket konnte nicht installiert werden. Es wurden keine funktionsfähigen Plugins gefunden.

Plugin-Installation fehlgeschlagen.

**Comment by Mirko45326** [comment]
Im Zip-Archiv befinden sich lediglich die beiden Dateien

"LICENCE" und "README.md"

**Comment by poilu** [comment]
README.md wurde entsprechend ergänzt. Änderungen erfolgen nur im development-Zweig, bis stabile Version erreicht ist.
